[33mcommit 79ba4e6a3b96de2a5f873f9fa341e64979ba085c[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m)[m
Author: Aritra Ghosh <aritraghosh184@gmail.com>
Date:   Mon Jul 14 00:06:10 2025 +0530

    Manually organized week 4 files into week4 folder

week3/Exercise2_3_RetailStore/Data/AppDbContext.cs
week3/Exercise2_3_RetailStore/Exercise2&3_output.jpg
week3/Exercise2_3_RetailStore/Exercise2-RetailStore.csproj
week3/Exercise2_3_RetailStore/Migrations/20250705205815_InitialCreate.Designer.cs
week3/Exercise2_3_RetailStore/Migrations/20250705205815_InitialCreate.cs
week3/Exercise2_3_RetailStore/Migrations/AppDbContextModelSnapshot.cs
week3/Exercise2_3_RetailStore/Models/Category.cs
week3/Exercise2_3_RetailStore/Models/Product.cs
week3/Exercise2_3_RetailStore/Program.cs
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Azure.Core.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Azure.Identity.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Exercise2-RetailStore.deps.json
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Exercise2-RetailStore.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Exercise2-RetailStore.exe
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Exercise2-RetailStore.pdb
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Exercise2-RetailStore.runtimeconfig.json
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Humanizer.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Bcl.AsyncInterfaces.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Build.Locator.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.CodeAnalysis.CSharp.Workspaces.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.CodeAnalysis.CSharp.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.CodeAnalysis.Workspaces.MSBuild.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.CodeAnalysis.Workspaces.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.CodeAnalysis.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Data.SqlClient.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.EntityFrameworkCore.Abstractions.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.EntityFrameworkCore.Design.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.EntityFrameworkCore.Relational.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.EntityFrameworkCore.SqlServer.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.EntityFrameworkCore.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.Caching.Abstractions.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.Caching.Memory.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.Configuration.Abstractions.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.DependencyInjection.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.DependencyModel.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.Logging.Abstractions.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.Logging.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.Options.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Extensions.Primitives.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Identity.Client.Extensions.Msal.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Identity.Client.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.IdentityModel.Abstractions.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.IdentityModel.JsonWebTokens.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.IdentityModel.Logging.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.IdentityModel.Protocols.OpenIdConnect.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.IdentityModel.Protocols.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.IdentityModel.Tokens.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.SqlServer.Server.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Microsoft.Win32.SystemEvents.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/Mono.TextTemplating.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.ClientModel.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.CodeDom.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Composition.AttributedModel.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Composition.Convention.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Composition.Hosting.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Composition.Runtime.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Composition.TypedParts.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Configuration.ConfigurationManager.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Drawing.Common.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.IdentityModel.Tokens.Jwt.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Memory.Data.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Runtime.Caching.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Security.Cryptography.ProtectedData.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Security.Permissions.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/System.Windows.Extensions.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/cs/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/cs/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/cs/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/cs/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/cs/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/de/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/de/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/de/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/de/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/de/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/es/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/es/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/es/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/es/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/es/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/fr/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/fr/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/fr/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/fr/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/fr/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/it/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/it/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/it/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/it/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/it/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ja/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ja/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ja/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ja/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ja/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ko/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ko/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ko/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ko/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ko/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pl/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pl/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pl/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pl/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pl/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pt-BR/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pt-BR/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pt-BR/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pt-BR/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/pt-BR/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ru/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ru/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ru/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ru/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/ru/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/unix/lib/net6.0/Microsoft.Data.SqlClient.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/unix/lib/net6.0/System.Drawing.Common.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win-arm/native/Microsoft.Data.SqlClient.SNI.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win-arm64/native/Microsoft.Data.SqlClient.SNI.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win-x64/native/Microsoft.Data.SqlClient.SNI.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win-x86/native/Microsoft.Data.SqlClient.SNI.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win/lib/net6.0/Microsoft.Data.SqlClient.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win/lib/net6.0/Microsoft.Win32.SystemEvents.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win/lib/net6.0/System.Drawing.Common.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win/lib/net6.0/System.Runtime.Caching.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win/lib/net6.0/System.Security.Cryptography.ProtectedData.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/runtimes/win/lib/net6.0/System.Windows.Extensions.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/tr/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/tr/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/tr/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/tr/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/tr/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hans/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hans/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hans/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hans/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hans/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hant/Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hant/Microsoft.CodeAnalysis.CSharp.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hant/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hant/Microsoft.CodeAnalysis.Workspaces.resources.dll
week3/Exercise2_3_RetailStore/bin/Debug/net9.0/zh-Hant/Microsoft.CodeAnalysis.resources.dll
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/.NETCoreApp,Version=v9.0.AssemblyAttributes.cs
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise.BEC682CC.Up2Date
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.AssemblyInfo.cs
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.AssemblyInfoInputs.cache
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.GeneratedMSBuildEditorConfig.editorconfig
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.GlobalUsings.g.cs
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.assets.cache
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.csproj.AssemblyReference.cache
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.csproj.CoreCompileInputs.cache
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.csproj.FileListAbsolute.txt
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.dll
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.genruntimeconfig.cache
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.pdb
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/Exercise2-RetailStore.sourcelink.json
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/apphost.exe
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/ref/Exercise2-RetailStore.dll
week3/Exercise2_3_RetailStore/obj/Debug/net9.0/refint/Exercise2-RetailStore.dll
week3/Exercise2_3_RetailStore/obj/Exercise2-RetailStore.csproj.EntityFrameworkCore.targets
week3/Exercise2_3_RetailStore/obj/Exercise2-RetailStore.csproj.nuget.dgspec.json
week3/Exercise2_3_RetailStore/obj/Exercise2-RetailStore.csproj.nuget.g.props
week3/Exercise2_3_RetailStore/obj/Exercise2-RetailStore.csproj.nuget.g.targets
week3/Exercise2_3_RetailStore/obj/project.assets.json
week3/Exercise2_3_RetailStore/obj/project.nuget.cache
week4
